### ISSUE TITLE
180 and 183 Issue in Sofia Sip Stack Version 1.13.6

### ISSUE THREAD

**Issue by Sivasundareswaran** [freeswitch/sofia-sip#106]
Hi Team ,

Client sending 183 and 180 with SDP , 183 is hitting in app_callback function but 180 is not hitting in app_callback function .

Thanks ,
Sivasundareswaran

**Comment by xadhoom** [comment]
I think this is the same as https://github.com/freeswitch/sofia-sip/issues/117 which is fixed by PR https://github.com/freeswitch/sofia-sip/pull/118

**Comment by andywolk** [comment]
https://github.com/freeswitch/sofia-sip/pull/118
