### ISSUE TITLE
sofia-sip will not build some file on non-x86?

### ISSUE THREAD

**Issue by yuzibo** [freeswitch/sofia-sip#113]
Hi,
I am tracking the thread to push myself to port riscv  on Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978498
And i follow the Debian's cross-compiling instruction and apply the patch from the thread.
I got the error at last:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978498#39

And build arch with armhf the result is same.
So I am confirm these files missing will or not compile on those non-x86 platform?

**Comment by mjerris** [comment]
we would appreciate patches to go in to tree that will support this work for all in a way that doesn’t break other platforms, as opposed to packaging system patches.  are you able to create the necessary changes?

**Comment by yuzibo** [comment]
No.
I am struggling with it to make change as you said.  But if it was true as descrption in the issue title, that will increase my confidence to go on.



---- 回复的原邮件 ----
| 发件人 | Michael ***@***.***> |
| 日期 | 2022年02月20日 03:11 |
| 收件人 | ***@***.***> |
| 抄送至 | Bo ***@***.******@***.***> |
| 主题 | Re: [freeswitch/sofia-sip] sofia-sip will not build some file on non-x86? (Issue #113) |

we would appreciate patches to go in to tree that will support this work for all in a way that doesn’t break other platforms, as opposed to packaging system patches. are you able to create the necessary changes?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuzibo** [comment]
Hi，
The [patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=978498;filename=sofia-sip-retooling.patch;msg=10) is ok.
It can build riscv deb package when i try Adrian‘s [method](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978498#44).
So, I can close the issue, thx.
