### ISSUE TITLE
A lock is missed to be released at error handling

### ISSUE THREAD

**Issue by ryancaicse** [freeswitch/sofia-sip#115]
Hi, should the lock `self->sup_obtained` also be released before returning at 140
https://github.com/freeswitch/sofia-sip/blob/18ce20ba40f9112876448c74d0aacbce0e34b372/libsofia-sip-ua/su/su_pthread_port.c#L138-L143

**Comment by andywolk** [comment]
No. You can not unlock if it is not locked or locked by another thread.
