### ISSUE TITLE
WSS errors because of SSL_Shutdown() after close()

### ISSUE THREAD

**Issue by kukies007** [freeswitch/sofia-sip#131]
Hello,

we have recognized issues when wss connections are closed and the socket is reused by another connection.

When looking at **ws_destroy()** in **ws.c** we can see that **SSL_shutdown()** is called after **close()** of a socket.  
We also recognized that ws_destroy() is sometimes called far after ws_close().
But **_"SSL_shutdown() tries to send the close_notify shutdown alert to the peer"_** (from openssl docs). 
To send the TLS close notify it uses the socket handle that is still stored in the ssl connection context. But since the socket is already closed its socket handle could be reused for another connection. So the TLS close notify will be send over the wrong connection.

With this bug we have seen invalid TLS packets on other WSS connections which breaks the new TLS session.
We have also seen invalid TLS packets on ESL connections. This will break proper receive handling of ESL events.

To solve these problems we think that SSL_shutodwn() must always be called before calling close() for the socket.

We have run some tests changing ws_close() to call SSL_shutdown() before closing the socket. This seems to fix all recognized problems.

**Comment by andywolk** [comment]
Will be happy to review your PRs.

**Comment by kukies007** [comment]
Thanks for your reply. Sadly I`m not very familiar with github and sofia code. Maybe there is someone that can check this problem and think about a proper solution.

**Comment by kukies007** [comment]
see Pull request #132
