### ISSUE TITLE
debian glib bindings

### ISSUE THREAD

**Issue by matt9j** [freeswitch/sofia-sip#15]
Hi! With the latest freeswitch 1.10.4 release it appears the debian-release repo now ships a binary for `libsofia-sip-ua0` with a version number of `1.12.12-20~f5d44540d3~buster`, and that usage of this library is required to run freeswitch (I get missing symbol errors in mod_sofia without it). debian10(buster) provides glib bindings for their version of libsofia-sip-ua0 via the libsofia-sip-ua-glib3 package, that some applications of interest (the osmocom cellular core network sip connector) depend on. These bindings are specific to the build of the library. Would this project be willing to re-enable glib bindings for their build to not break compatibility with other debian software? I can provide a pull request for this support, but wanted to open a tracking issue for discussion.

Thanks for your work supporting and keeping this library up to date-- the official debian version is quite old by comparison!

**Comment by andywolk** [comment]
See PR #17

**Comment by matt9j** [comment]
I opened a PR with the glib package building metadata as well https://github.com/freeswitch/sofia-sip/pull/18

**Comment by matt9j** [comment]
I believe this should now be resolved. Thanks andywolk and s3rj1k!
