### ISSUE TITLE
TCP sockets file descriptor leaks on truncated websocket connections.

### ISSUE THREAD

**Issue by xadhoom** [freeswitch/sofia-sip#162]
Sofia leaks tcp sockets file descriptors when trying to reach a ws/wss endpoint, which is not supported (afaik).

Easily reproducible scenario:
- a subscribe initiated over the websocket
- the client disappears never clearing the subscribe
- freeswitch tries to send notifiy, ws/wss is disconnected, so sofia tries to connect to the endpoint via wss:ipaddr:port

But this is a websocket and sofia does not khow to handle it, so in tport_connect -> tport_base_connect is called, which allocates a socket that is never cleared because connect() fails with the error "transport endpoint is not connected".

**Comment by xadhoom** [comment]
I've proposed a possible fix (verified) in #163

**Comment by andywolk** [comment]
Fixed by https://github.com/freeswitch/sofia-sip/pull/233
