### ISSUE TITLE
sip.js websocket terminated by Freeswitch error 1006

### ISSUE THREAD

**Issue by jerry6021** [freeswitch/sofia-sip#172]
Has there been progress on this issue?

still have it with the latest version.

debian 10
FS 1.10.6
libsofia-sip-au 1.13.8
Lets Encrypt
WSS

we get the 1006 error very randomly...
After 3 weeks of trying to get WSS working, there is no noticeable pattern to the failures...

I will upload some log info and such sortly..

**Comment by jerry6021** [comment]
Here is today's debug capture with
TPORT_DEBUG=9
SOFIA_DEBUG=9

**Comment by jerry6021** [comment]
tport.c:3059 tport_deliver() tport_deliver(0x7f8408a94d50): msg 0x7f840815a6e0 (515 bytes) from wss/<CLIENT_NATED_IP>:50953/sips next=(nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408acae60 by 0x7f84085c29c0 with 0x7f840815a6e0
tport.c:2316 tport_set_secondary_timer() tport(0x7f8408a94d50): reset timer
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408e360e0 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 497 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): msg 0x7f8408e360e0 (497 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:4258 tport_release() tport_release(0x7f8408006290): 0x7f8409a70920 by 0x7f8408e58960 with 0x7f8408e360e0
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f84088ca010 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 375 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): msg 0x7f84088ca010 (375 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:4258 tport_release() tport_release(0x7f8408006290): 0x7f8409387b60 by 0x7f8408548810 with 0x7f84088ca010
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408f044e0 by 0x7f8408f05560 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f84087a0220 by 0x7f84087a12a0 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f84087b5710 by 0x7f84087b6790 with (nil)
tport.c:2278 tport_set_secondary_timer() tport(0x7f84094d1590): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f84080c37f0): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f840823e3c0): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f8408288900): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f8408605b60): set timer at 0 ms because zap
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f84087dd730 by 0x7f84087de7b0 with (nil)
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f84094d1590 destroy wss transport 0x7f84094d1780.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f84080c37f0 destroy wss transport 0x7f84080c39e0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f840823e3c0 destroy wss transport 0x7f840823e5b0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f8408288900 destroy wss transport 0x7f8408288af0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f8408605b60 destroy wss transport 0x7f8408605d50.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport.c:2278 tport_set_secondary_timer() tport(0x7f8408fe23e0): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f84088db380): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f84080340e0): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f8408b5bed0): set timer at 0 ms because zap
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f8408fe23e0 destroy wss transport 0x7f8408fe25d0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f84088db380 destroy wss transport 0x7f84088db570.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f84080340e0 destroy wss transport 0x7f84080342d0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f8408b5bed0 destroy wss transport 0x7f8408b5c0c0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408b3f100 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 579 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): msg 0x7f8408b3f100 (579 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:3293 tport_tsend() tport_tsend(0x7f8408006290) tpn = UDP/<CLIENT_NATED_IP>:46364
tport.c:4082 tport_resolve() tport_resolve addrinfo = <CLIENT_NATED_IP>:46364
tport.c:4716 tport_by_addrinfo() tport_by_addrinfo(0x7f8408006290): not found by name UDP/<CLIENT_NATED_IP>:46364
tport.c:3630 tport_vsend() tport_vsend(0x7f8408006290): 734 bytes of 734 to udp/<CLIENT_NATED_IP>:46364
tport.c:3528 tport_send_msg() tport_vsend returned 734
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408433200 by 0x7f84083ec2c0 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8409071760 by 0x7f84090727e0 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8409088520 by 0x7f84090895a0 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f84090b08b0 by 0x7f84090b1930 with (nil)
tport.c:2802 tport_wakeup() tport_wakeup(0x7f8408a94d50): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408a94d50)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408a94d50) msg 0x7f8408144390 from (wss/<CLIENT_NATED_IP>:50953) has 401 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408a94d50): msg 0x7f8408144390 (401 bytes) from wss/<CLIENT_NATED_IP>:50953/sips next=(nil)
tport.c:3293 tport_tsend() tport_tsend(0x7f8408a94d50) tpn = WSS/<CLIENT_NATED_IP>:5060
tport_type_ws.c:328 tport_send_stream_ws() tport_ws_writevec: vec 0x7f8408a94f40 0x7f84086a4880 331 (0)
tport.c:3630 tport_vsend() tport_vsend(0x7f8408a94d50): 331 bytes of 331 to wss/<CLIENT_NATED_IP>:50953
tport.c:3528 tport_send_msg() tport_vsend returned 331
tport.c:2316 tport_set_secondary_timer() tport(0x7f8408a94d50): reset timer
tport.c:3293 tport_tsend() tport_tsend(0x7f8408a94d50) tpn = WSS/<CLIENT_NATED_IP>:50953
tport_type_ws.c:328 tport_send_stream_ws() tport_ws_writevec: vec 0x7f8408a94f40 0x7f84086a4880 685 (0)
tport.c:3630 tport_vsend() tport_vsend(0x7f8408a94d50): 685 bytes of 685 to wss/<CLIENT_NATED_IP>:50953
tport.c:3528 tport_send_msg() tport_vsend returned 685
tport.c:2316 tport_set_secondary_timer() tport(0x7f8408a94d50): reset timer
tport.c:2316 tport_set_secondary_timer() tport(0x7f8408a94d50): reset timer
tport.c:2802 tport_wakeup() tport_wakeup(0x7f8408a94d50): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408a94d50)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408a94d50) msg 0x7f84086c3610 from (wss/<CLIENT_NATED_IP>:50953) has 351 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408a94d50): msg 0x7f84086c3610 (351 bytes) from wss/<CLIENT_NATED_IP>:50953/sips next=(nil)
tport.c:2316 tport_set_secondary_timer() tport(0x7f8408a94d50): reset timer
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f840907c9a0 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 574 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): msg 0x7f840907c9a0 (574 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:3293 tport_tsend() tport_tsend(0x7f8408006290) tpn = UDP/<CLIENT_NATED_IP>:23554
tport.c:4082 tport_resolve() tport_resolve addrinfo = <CLIENT_NATED_IP>:23554
tport.c:4716 tport_by_addrinfo() tport_by_addrinfo(0x7f8408006290): not found by name UDP/<CLIENT_NATED_IP>:23554
tport.c:3630 tport_vsend() tport_vsend(0x7f8408006290): 730 bytes of 730 to udp/<CLIENT_NATED_IP>:23554
tport.c:3528 tport_send_msg() tport_vsend returned 730
tport.c:3293 tport_tsend() tport_tsend(0x7f8408006290) tpn = udp/<CLIENT_NATED_IP>:51651
tport.c:4082 tport_resolve() tport_resolve addrinfo = <CLIENT_NATED_IP>:51651
tport.c:4716 tport_by_addrinfo() tport_by_addrinfo(0x7f8408006290): not found by name udp/<CLIENT_NATED_IP>:51651
tport.c:3630 tport_vsend() tport_vsend(0x7f8408006290): 794 bytes of 794 to udp/<CLIENT_NATED_IP>:51651
tport.c:3528 tport_send_msg() tport_vsend returned 794
tport.c:4196 tport_pend() tport_pend(0x7f8408006290): pending 0x7f8409484ca0 for udp/<FreeSWITCH_PUBLIC_IP>:<PORT> (already 1)
tport.c:3293 tport_tsend() tport_tsend(0x7f8408006290) tpn = */<CLIENT_NATED_IP>:46364
tport.c:4082 tport_resolve() tport_resolve addrinfo = <CLIENT_NATED_IP>:46364
tport.c:4716 tport_by_addrinfo() tport_by_addrinfo(0x7f8408006290): not found by name */<CLIENT_NATED_IP>:46364
tport.c:3630 tport_vsend() tport_vsend(0x7f8408006290): 787 bytes of 787 to udp/<CLIENT_NATED_IP>:46364
tport.c:3528 tport_send_msg() tport_vsend returned 787
tport.c:4196 tport_pend() tport_pend(0x7f8408006290): pending 0x7f8408e5e5e0 for udp/<FreeSWITCH_PUBLIC_IP>:<PORT> (already 2)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f840913f860 by 0x7f84091408e0 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8409168c20 by 0x7f8409169ca0 with (nil)
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f84082cf0f0 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 506 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): msg 0x7f84082cf0f0 (506 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:4258 tport_release() tport_release(0x7f8408006290): 0x7f8408e5e5e0 by 0x7f8408307bc0 with 0x7f84082cf0f0
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408bac4b0 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 288 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): msg 0x7f8408bac4b0 (288 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:4258 tport_release() tport_release(0x7f8408006290): 0x7f8409484ca0 by 0x7f840884f1d0 with 0x7f8408bac4b0
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408d3cc20 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 20 bytes, veclen = 1
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408fd0860 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 4 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): bad msg 0x7f8408fd0860 (4 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f84090eb820 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 4 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): bad msg 0x7f84090eb820 (4 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408bf3ec0 by 0x7f8408bf4f40 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408c1bf70 by 0x7f8408c1cff0 with (nil)
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408550a40 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 20 bytes, veclen = 1
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408ca9ad0 by 0x7f8408caab50 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408cd2e70 by 0x7f8408cd3ef0 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408ce2220 by 0x7f8408ce32a0 with (nil)
tport.c:2278 tport_set_secondary_timer() tport(0x7f84086d7d40): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f840871e4e0): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f840835ecc0): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f84083a5870): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f84083ec420): set timer at 0 ms because zap
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f8408d0a210 by 0x7f8408d0b290 with (nil)
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f84086d7d40 destroy wss transport 0x7f84086d7f30.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f840871e4e0 destroy wss transport 0x7f840871e6d0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f840835ecc0 destroy wss transport 0x7f840835eeb0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f84083a5870 destroy wss transport 0x7f84083a5a60.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f84083ec420 destroy wss transport 0x7f84083ec610.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport.c:2278 tport_set_secondary_timer() tport(0x7f8408d815d0): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f8408db5970): set timer at 0 ms because zap
tport.c:2278 tport_set_secondary_timer() tport(0x7f8408df5c60): set timer at 0 ms because zap
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f8408d815d0 destroy wss transport 0x7f8408d817c0.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f8408db5970 destroy wss transport 0x7f8408db5b60.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f8408df5c60 destroy wss transport 0x7f8408df5e50.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport.c:2278 tport_set_secondary_timer() tport(0x7f840865be80): set timer at 0 ms because zap
tport_type_ws.c:546 tport_ws_deinit_secondary() 0x7f840865be80 destroy wss transport 0x7f840865c070.
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 00000001:(null):(null):(null)
ws.c:447 wss_log_errors() ws_destroy: SSL_shutdown: 140e0197:SSL routines:SSL_shutdown:shutdown while in init
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f84092de880 by 0x7f84091dd3c0 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f84092ffd90 by 0x7f8409300e10 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f84093256b0 by 0x7f8409326730 with (nil)
tport.c:4258 tport_release() tport_release(0x7f8408a94d50): 0x7f840934db80 by 0x7f840934ec00 with (nil)
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408fa0fb0 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 4 bytes, veclen = 1
tport.c:3059 tport_deliver() tport_deliver(0x7f8408006290): bad msg 0x7f8408fa0fb0 (4 bytes) from udp/<CLIENT_NATED_IP>:<PORT>/sip next=(nil)
tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7f8408006290): events IN
tport.c:2900 tport_recv_event() tport_recv_event(0x7f8408006290)
tport.c:3241 tport_recv_iovec() tport_recv_iovec(0x7f8408006290) msg 0x7f8408c8dca0 from (udp/<FreeSWITCH_PUBLIC_IP>:<PORT>) has 20 bytes, veclen = 1

**Comment by jerry6021** [comment]
Maybe, someone can point me at the messages that are indicating a problem...

I have the source and have added lots of debug messages but they are #ifdef'd out at the moment.

I can certainly add them in or add more but I need guidance as to where to look.

**Comment by jerry6021** [comment]
I see quite a few of these types of lines:
tport.c:3059 tport_deliver() tport_deliver(0x7f5290006290): bad msg 0x7f52903e2840 (4 bytes) from udp/<CLIENT_IP>:<PORT>/sip next=(nil)

Oddly though, the PORT number makes NO sense... the IP is right but the network traffic is NOT from the port shown...

**Comment by jerry6021** [comment]
Got a bunch of ERR....

**Comment by andywolk** [comment]
See https://github.com/freeswitch/sofia-sip/pull/175
