### ISSUE TITLE
location of prebuild binaries of the library

### ISSUE THREAD

**Issue by ehrenmann1977** [freeswitch/sofia-sip#193]
i am struggling to compile the windows library, therefore i would like to ask where to find the pre built binaries of the library, for ios (iPhone), windows, Linux and mac. This would be great so that i can contribute.

**Comment by andywolk** [comment]
We do not produce pre-compiled binaries for this library. On the other hand `sofia-sip` is a part of the build of the FreeSWITCH solution in Visual Studio on Windows. You may take a look at how FreeSWITCH is build. And this is the vcxproj of sofia-sip: https://github.com/signalwire/freeswitch/blob/master/libs/win32/sofia/libsofia_sip_ua_static.2017.vcxproj 
That may help.
