### ISSUE TITLE
sofia thread can hang for several minutes when closing wss connection that was never established

### ISSUE THREAD

**Issue by davehorton** [freeswitch/sofia-sip#212]
This code in `ws_close()`

https://github.com/freeswitch/sofia-sip/blob/3f17604d0c427a276839ea96b6dc31d7da69d27c/libsofia-sip-ua/tport/ws.c#L825

has the potential to hanging the sofia main thread and blocking all incoming and outgoing messages for several minutes.  Note that the socket has been put back in blocking mode at this point, and if the attempt to send one byte fails the thread will block for several minutes.  This is the case where the socket was either never connected or TLS handshake did not complete.

For example, one scenario that causes this which I have observed:
- process sends an INVITE to a webrtc client over established wss connection
- webrtc client sends 100 Trying, then 180 Ringing, then abruptly closes the wss connection
- later, the process wants to send a CANCELto the client
- sofia will allocate a new secondary tport to try to reach the remote ip:port, `ws_init` will be called as part of this, but the connection attempt will fail since the remote client is not listening on that port
- later, sofia timer will cause the new tport to be closed
- since `ws_init` was called, we do have a `wsh->ssl` so the code above will execute and SSL_write will be called
- the thread will block several minutes, during which network traffic is not processed

**Comment by seven1240** [comment]
https://www.openssl.org/docs/manmaster/man3/SSL_shutdown.html  After SSL_shutdown() returned 0, it is possible to call SSL_shutdown() again to wait for the peer's close_notify alert. SSL_shutdown() will return 1 in that case. However, it is recommended to wait for it using SSL_read() instead.

Someone in the Chinese community also mentioned that and reported revert back to some old version works. maybe related to e77e70d8447a1220f0a27b431149543a8a43bca5 .

**Comment by davehorton** [comment]
> Someone in the Chinese community also mentioned that and reported revert back to some old version works. maybe related to [e77e70d](https://github.com/freeswitch/sofia-sip/commit/e77e70d8447a1220f0a27b431149543a8a43bca5) .

Yes, I think that PR introduced this issue, as best I can tell

**Comment by seven1240** [comment]
there's a patch might be related to this: https://github.com/freeswitch/sofia-sip/pull/222/files?diff=unified&w=1

**Comment by themsley-voiceflex** [comment]
Far more likely to be the issue in #2283 where SSL_ERROR_SSL and SSL_ERROR_SYSCALL are ignored - by which time the socket is already closed and gone from the system and then ws_close() is called with a dangling wsh->sock pointing to the socket that was already gone. My patch from 2283 PR 231 fixes the underlying cause though maybe not in the right way. But it works...

**Comment by jakubkarolczyk** [comment]
@davehorton please try this PR https://github.com/freeswitch/sofia-sip/pull/233

**Comment by andywolk** [comment]
PR #233 has been merged.
