### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by ajs124** [freeswitch/sofia-sip#24]
Hey, for distro packaging (e.g. https://github.com/NixOS/nixpkgs/pull/96987) it would be nice to have tagged releases.

For 1.13 a commit like f6f29b483e9c31ce8d3e87419ec3deea8679312d looks about right.

**Comment by jonasstein** [comment]
This would help us also for https://bugs.gentoo.org/747646 Please add tags for the releases. Thank you very much.

**Comment by ajs124** [comment]
Somebody just created https://github.com/freeswitch/sofia-sip/releases/tag/v1.13.2, so I'll close this for now.

**Comment by andywolk** [comment]
Yeah, there were some pretty important changes so this new version deserves to exist.
