### ISSUE TITLE
Repo version tagging

### ISSUE THREAD

**Issue by rmackinnon** [freeswitch/sofia-sip#30]
Could we get some tags on the repo for versions?
E.g. v1.12.x or v1.13

Would help getting build automation to run cleaner for downstream use.

**Comment by traud** [comment]
+1 one from me. However, this is a [duplicate …](https://github.com/freeswitch/sofia-sip/issues/24)

**Comment by rmackinnon** [comment]
-_o_- great minds think a like? Thanks in advance.
