### ISSUE TITLE
transport tls is not supported ?

### ISSUE THREAD

**Issue by fortysixandtwo** [freeswitch/sofia-sip#40]
On the current master (and also with the package available in debian 1.12.11) 
I'm having trouble connecting securely (over tls) with a server.
The problem persists no matter which client/tool (sip-options, sofsip_cli, empathy or my own code) I'm using.

Running with `SOFIA_DEBUG` set I usually get errors like
`nta(0x558295c0fef0): transport tls is not supported`
or `nta outgoing create: no transport protocol`

Here you can find a sample session with `sip-options`
```
$ SOFIA_DEBUG=3 sip-options -a "sip:pbx-ext.chilly.cloud;transport=tls" 
nta(0x558295c0fef0): transport tls is not supported 
SIP/2.0 503 DNS Error 
Via: SIP/2.0/UDP 10.0.2.15:60666;branch=z9hG4bKDF709t04eX92F 
From: sip:10.0.2.15;tag=D1NHX8yrKrZFQ 
To: sip:pbx-ext.chilly.cloud;tag=eaFaZ3Fvg1N2j 
Call-ID: b5898b23-b898-1239-59a7-525400123456 
CSeq: 954232495 OPTIONS 
Content-Length: 0
```
It says `DNS Error` but I can't find any queries in my resolvers logs.

This time using the ip instead of domain name
```
$ SOFIA_DEBUG=3 sip-options -a "sip:208.97.62.12:5061;transport=tls"
nta outgoing create: no transport protocol
SIP/2.0 503 No transport
Via: SIP/2.0/UDP 10.0.2.15:60139;branch=z9hG4bKUcgvc8aregZ2r
From: sip:10.0.2.15;tag=Uv5c56r2ZKKBN
To: sip:208.97.62.12;tag=v5y56195vv9Xg
Call-ID: a6335111-b960-1239-bfb3-525400123456
CSeq: 954253963 OPTIONS
Content-Length: 0
```

**Comment by mjerris** [comment]
sounds like a build issue.  if you built yourself try our packages or more closely follow build instructions for a platform we support well

**Comment by fortysixandtwo** [comment]
Thanks for your answer!

I'm running debian bullseye and have tried it three different ways:
- Using the packaging currently in debian (see https://snapshot.debian.org/package/sofia-sip/1.12.11%2B20110422.1-2.1/)
- Building the debian package myself from master (see https://github.com/freeswitch/sofia-sip/blob/master/debian/rules#L10 )
- Building myself (`./autogen.sh && ./configure --prefix ${HOME}/install && make && make install` - I used the prefix to not pollute my /usr and have made sure to set LD_LIBRARY_PATH accordingly and verified in this case with ldd that the correct library would be used and also verified with ldd that the built library uses )

By build instroctions you mean:
https://github.com/freeswitch/sofia-sip/blob/master/docs/build_system.txt

Having a look at the flags for the configure script, I'm not sure I need to explicitly enable/disable any features to get TLS connections working.

So from your question I take it, that the `sip-options` invocation from above works for you (with the current master)?

**Comment by fortysixandtwo** [comment]
@mjerris Quick update: I have installed Debian 10 (Buster) to a fresh VM
added the freeswitch repositories as per https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster
and still got the same error `transport tls is not supported` when f.e. trying `SOFIA_DEBUG=3 sip-options -a "sip:pbx-ext.chilly.cloud;transport=tls"`

**Comment by azzbcc** [comment]
Add `--bind="sips:*:*"` so that we can use `tports_sips` which provides `tls` protocol.

**Comment by fortysixandtwo** [comment]
Thanks a lot @azzbcc , adding that bind flags made all the difference!
Closing the issue.
