### ISSUE TITLE
SDP parser doesn't associate PTIME value with corresponding codec in SDP with multiple audio media entries

### ISSUE THREAD

**Issue by figaro2015** [freeswitch/sofia-sip#46]
SOFIA-SIP SDP parser doesn't associate CODEC entry with corresponding PTIME value while parsing SDP with multiple audio media entries. Like for example: 

m=audio [media_port] RTP/AVP 96 9 124 104 105 0 8 116 15 3 18 4 101
      a=rtpmap:96 mpeg4-generic/0/0
      a=fmtp:96 profile-level-id=0;mode=generic
      a=rtpmap:9 G722/8000
      a=ptime:20
      a=rtpmap:124 iSAC/16000
      a=rtpmap:104 G7221/16000
      a=fmtp:104 bitrate=32000
      a=ptime:60
      a=rtpmap:105 G7221/16000
      a=fmtp:105 bitrate=24000
      a=ptime:60
      a=rtpmap:0 PCMU/8000
      a=ptime:40
      a=rtpmap:8 PCMA/8000
      a=ptime:20
      a=rtpmap:116 iLBC/8000
      a=ptime:60
      a=maxptime:60
      a=fmtp:116 mode=30
      a=rtpmap:15 G728/8000
      a=ptime:30
      a=rtpmap:3 GSM/8000
      a=ptime:20
      a=rtpmap:4 G723/8000
      a=ptime:30
      a=rtpmap:18 G729/8000
      a=ptime:20
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-15

As a result of that, it forces application code (like for example FreeSWITCH mod_sofia module) that uses parsed by SOFIA-SIP stack SDP to use the last PTIME value for any of the negotiated CODEC entries.

**Comment by mjerris** [comment]
This is because that’s not how sdp ptime attributes work.  Check the rfc’s for sdp for more info.
