### ISSUE TITLE
How to force new TCP/TLS connection for every new outgoing call?

### ISSUE THREAD

**Issue by TelephonyMan** [freeswitch/sofia-sip#63]
We are making outgoing calls to a load-balanced SBC which has two nodes. Since freeswitch is reusing the same open TCP/TLS socket to the SBC for every outgoing call, the load is not getting distributed across the two nodes of the SBC. All the calls are going to the same node.

If we can force each new call to use a different TCP connection, the load will get distributed evenly. Is there any configuration that makes this possible?

**Comment by abma** [comment]
we are using python for the dialplan and solved this by using a random bridge string:

 ```
 import random
 trunks = [
     "sofia/gateway/gw1/%s" % (number),
     "sofia/gateway/gw2/%s" % (number)
 ]
 random.shuffle(trunks)
 session.execute("bridge", "|".join(trunks))
```

as the xml dialplan supports random numbers, it should be doable in a similar way:
https://freeswitch.org/confluence/display/FREESWITCH/mod_expr#mod_expr-Dialplan
+
https://freeswitch.org/confluence/display/FREESWITCH/mod_dptools%3A+bridge#mod_dptools:bridge-3.6ImplementingFailover

**Comment by TelephonyMan** [comment]
Thanks. We tried this, but if all gateways point to the same load-balancer IP address, freeswitch doesn't get fooled.

But wait, what if we have multiple IP addresses for the load-balancer... that's worth trying. Will try that next.
